---
id: mysql-and-postgresql-and-japanese-full-text-search-2
base_name: mroonga-and-pgroonga
tags:
- rabbit
- mroonga
- mysql
- pgroonga
- postgresql
- full-text-search
presentation_date: 2016-06-09
version: 2016.6.9.0
licenses:
- CC BY 3.0
- CC BY-SA 4.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
